"""Browser acceptance checks for composition entry, editable plans and compact export."""
from grid_helpers import *
from openpyxl import load_workbook

with sync_playwright() as pw:
    browser = pw.chromium.launch(channel='chrome', headless=True)
    page = browser.new_page(viewport={'width': 1280, 'height': 860}, accept_downloads=True)
    page.goto(URL)
    settle(page, 4)
    click(page, 'Try the sample project')
    assert not page.locator('[data-testid="stException"]').count()
    assert not page.get_by_text('Example project', exact=True).count()
    page.get_by_text('Calculation help', exact=True).click()
    settle(page)
    assert page.get_by_text('Top up to the batch size', exact=False).count()
    page.keyboard.press('Escape')
    open_fold(page, 'Dry blend · parts')
    parts = grid_named(page, 'Part')
    assert 'Unit' not in grid_head(page, parts)
    assert 'Composition (%)' in grid_head(page, parts)
    page.screenshot(path='/tmp/foodopt-ux-composition.png', full_page=True)
    group = fold(page, 'Dry blend · parts')
    group.get_by_text('Enter a weighed recipe instead', exact=True).click()
    settle(page)
    parts = grid_named(page, 'Part')
    print('Amount entry headers:', grid_head(page, parts), flush=True)
    assert 'Amount (g)' in grid_head(page, parts)
    set_cell(page, parts, 0, 1, '60')
    fold_click(page, 'Dry blend · parts', 'Save changes')
    assert not alerts(page, 'Error'), alerts(page, 'Error')
    open_fold(page, 'Dry blend · parts')
    group.get_by_text('Enter a weighed recipe instead', exact=True).click(); settle(page)
    parts = grid_named(page, 'Part')
    assert abs(float(grid_rows(page, parts)[0][1]) - 60/94*100) < 0.02
    print('PASS percentages / amounts conversion and save', flush=True)
    click(page, 'Generate formulations')
    generate = next(label for label in labels(page) if label.startswith('Generate') and 'different' not in label)
    click(page, generate, wait=5)
    click(page, 'Edit formulations')
    plan = grid_named(page, 'Formulation')
    print('Editable plan headers:', grid_head(page, plan), flush=True)
    set_cell(page, plan, 0, 1, '6')
    click(page, 'Save changes')
    assert not alerts(page, 'Error'), alerts(page, 'Error')
    assert not page.locator('[data-testid="stException"]').count()
    page.screenshot(path='/tmp/foodopt-ux-round.png', full_page=True)
    with page.expect_download() as event:
        page.get_by_role('button', name='Download the round sheets (Excel)', exact=True).click()
    path = '/tmp/foodopt-ux-round.xlsx'
    event.value.save_as(path)
    book = load_workbook(path)
    assert book.sheetnames == ['Round overview', 'Preparation', 'Results']
    print('PASS edit and three-tab workbook download', flush=True)
    browser.close()
